[tool.poetry]
name = "tomos"
version = "0.1.4.beta"
description = "Code Tomographies for AyED2"
authors = ["Javier Mansilla <javimansilla@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
lark = "^1.2.2"
docopt = "^0.6.2"
pygments = "^2.18.0"
pygments-ayed2 = "^0.1.2"
skitso = "^0.1.13"
prettytable = "^3.11.0"
moviepy = "^2.1.2"

six = "^1.17.0"  # dont know why pygments does not solve this

buttons-and-dials = "^0.1.3"

pydantic = "^2.10.6"
[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
factory-boy = "^3.3.1"

pytest-cov = "^6.0.0"
black = "^25.1.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tomos = "tomos.ui.cli:main"

[tool.black]
line-length = 100
