[project]
name = "delta-hybrid-scd"
version = "0.1.1"
description = "A package for implementing hybrid SCD1 and SCD2 operations using Delta Tables in Databricks"
authors = [
    {name = "Prateek Mishra"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyspark (>=3.5.5,<4.0.0)",
    "delta-spark (>=3.3.1,<4.0.0)",
    "databricks-api (>=0.9.0,<0.10.0)",
    "datetime (>=5.5,<6.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
