[project]
name = "chronotrack-cli"
version = "0.1.7"
description = "A developer-focused CLI time tracker with tagging, breaks, and rich analytics."
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
authors = [
    {name = "Shahriyar Ahmed Mahir", email = "nafismahir@icloud.com"}
]
keywords = ["cli", "productivity", "time-tracking", "terminal", "typer"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]


[project.urls]
Homepage = "https://github.com/mahirvisoredbroom855/ChronoTrack"
Repository = "https://github.com/mahirvisoredbroom855/ChronoTrack"
Issues = "https://github.com/mahirvisoredbroom855/ChronoTrack/issues"

[project.scripts]
chronotrack = "chronotrack.cli:app"


[tool.setuptools.packages.find]
include = ["chronotrack"]


[tool.setuptools]
include-package-data = true

