[build-system]
requires = [
    "meson-python >= 0.13",
    "cython >= 3.0",
    "numpy",
    "cherab >= 1.5,<2.0",
    "tomli; python_version < '3.11'",
]
build-backend = "mesonpy"

[project]
name = "cherab-lhd"
description = "Cherab spectroscopy framework: LHD machine configuration"
version = "0.2.0"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE.md" }
authors = [
    { name = "Koyo Munechika", email = "munechika.koyo@torus.nr.titech.ac.jp" },
]
maintainers = [
    { name = "Koyo Munechika", email = "munechika.koyo@torus.nr.titech.ac.jp" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Cython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "numpy >=1.14,<2.0",
    "scipy",
    "matplotlib",
    "plotly",
    "h5py",
    "xarray",
    "netcdf4",
    "cherab >=1.5,<2.0",
    # "cherab-inversion",
    "rich",
    "pooch",
    "paramiko",
    "tqdm",
]

[project.urls]
Homepage = "https://cherab-lhd.readthedocs.io"
documentation = "https://cherab-lhd.readthedocs.io"
repository = "https://github.com/munechika-koyo/cherab_lhd"

# -----------------------
# === Cov/Test config ===
# -----------------------
[tool.coverage.run]
source_pkgs = ["cherab.lhd"]
branch = true
parallel = true

[tool.coverage.paths]
tests = ["tests", "*/test/tests"]

[tool.coverage.report]
exclude_lines = ["no cov", "if __name__ == .__main__.:", "if TYPE_CHECKING:"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov=cherab_lhd --cov-report term-missing --no-cov-on-fail"

# --------------------------
# === Lint/Format config ===
# --------------------------
[tool.cython-lint]
max-line-length = 100
ignore = ["E741"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "N", "B", "NPY"]
ignore = [
    "E501", # line too long (allow for docstrings)
    "N806", # variable in function should be lowercase
]

[tool.ruff.lint.per-file-ignores]
"**/*.ipynb" = ["W292"] # no newline at end of file
"cherab/lhd/emc3/grid.py" = ["E741"]
"cherab/lhd/emc3/barycenters.py" = ["E741"]
"cherab/lhd/emc3/curvilinear.py" = ["E741"]
"cherab/lhd/emc3/inversion/derivative.py" = ["E741"]

[tool.docformatter]
recursive = true
wrap-summaries = 100
wrap-descriptions = 100
blank = false

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true

[tool.numpydoc_validation]
checks = [
    "all",  # report on all checks, except the below
    "GL01", # Docstring text (summary) should start in the line immediately
    "EX01", # No examples section found
    "SA01", # See Also section not found
    "ES01", # No extended summary found
    "GL08", # The object does not have a docstring
    "RT01", # No Returns section found
    "PR01", # Parameters {missing_params} not documented
    "SS06", # Summary should fit in a single line
]
# remember to use single quotes for regex in TOML
exclude = [ # don't report on objects that match any of these regex
    '\.__repr__$',
]
override_SS05 = ['^Process ', '^Assess ', '^Access ']

# --------------------
# === Build config ===
# --------------------
[tool.cibuildwheel]
skip = "pp* *_ppc64le *_i686 *_s390x *-musllinux* cp313-*"
build-frontend = "build[uv]"
test-requires = ["pytest", "pytest-cov"]
test-command = "pytest {project}/tests"


# -------------------
# === Pixi config ===
# -------------------
[tool.pixi.project]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64"]

[tool.pixi.build-dependencies]
c-compiler = "*"

[tool.pixi.host-dependencies]
python = ">=3.10,<3.13"
meson-python = "*"
tomli = "*"  # if python_version < 3.11
cython = "*"
cherab = "*"

[tool.pixi.target.osx-arm64.host-dependencies]
llvm-openmp = "*"

[tool.pixi.dependencies]
numpy = ">=1.26.4,<3"
scipy = ">=1.15.2,<2"
cherab-inversion = ">=0.3.1,<0.4"
matplotlib = ">=3.10.0,<4"
plotly = ">=6.0.0,<7"
h5py = ">=3.13.0,<4"
xarray = ">=2025.1.2,<2026"
netcdf4 = ">=1.7.2,<2"
rich = ">=14.0.0,<15"
pooch = ">=1.8.2,<2"
paramiko = ">=3.5.1,<4"
tqdm = ">=4.67.1,<5"
ipython = ">=8.35.0,<10"
pyvista = ">=0.45.0,<0.46"

# Workaround for https://github.com/prefix-dev/pixi/issues/3479
[tool.pixi.target.osx-arm64.dependencies]
libgfortran5 = ">=14.2.0"

[tool.pixi.pypi-dependencies]
pymupdf = ">=1.25.3,<2"
cherab-lhd = { path = ".", editable = true }

[tool.pixi.pypi-options]
no-build-isolation = ["cherab-lhd"]

[tool.pixi.feature.lab.dependencies]
ipykernel = "*"
ipywidgets = "*"
jupyterlab = "*"
python-kaleido = "*"

[tool.pixi.feature.lab.tasks]
lab = { cmd = [
    "jupyter",
    "lab",
    "--notebook-dir",
    "docs/notebooks",
], description = "ðŸš€ Start JupyterLab" }

[tool.pixi.feature.docs.dependencies]
ipykernel = "*"
ipywidgets = "*"
nbconvert = "*"
nbsphinx = "*"
numpydoc = "*"
pillow = "*"
pygments = ">2.11.0"
sphinx = "<8.2"
sphinx-copybutton = "*"
pydata-sphinx-theme = "*"
sphinx-design = "*"
pandoc = "*"
sphinx-codeautolink = "*"
python-kaleido = "*"

[tool.pixi.feature.docs.pypi-dependencies]
sphinx-github-style = "*"

[tool.pixi.feature.docs.tasks]
doc-build = { cmd = [
    "sphinx-build",
    "-b",
    "html",
    "-j",
    "auto",
    "docs/source",
    "docs/build/html",
], description = "ðŸ“ Build the docs" }
doc-clean = { cmd = [
    "rm",
    "-rf",
    "docs/build",
    "docs/source/_api",
], description = "ðŸ”¥ Clean the docs build & api directory" }
doc-serve = { cmd = [
    "python",
    "-m",
    "http.server",
    "8000",
    "--directory",
    "docs/build/html",
], description = "ðŸš€ Start a local server for the docs" }

[tool.pixi.feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[tool.pixi.feature.test.pypi-dependencies]
pytest-github-report = "*"

[tool.pixi.feature.test.tasks]
test = { cmd = ["pytest", "tests"], description = "ðŸ§ª Run the tests" }

[tool.pixi.feature.lint.dependencies]
ruff = "*"
mypy = "*"
pre-commit = ">=4.2.0,<5"

[tool.pixi.feature.lint.tasks]
lint = { cmd = ["ruff", "check"], description = "ðŸ§¹ Lint the code" }
format = { cmd = ["ruff", "format"], description = "ðŸ§¹ Format the code" }
pre-commit-run = { cmd = [
    "pre-commit",
    "run",
    "--all-files",
], description = "ðŸ©º Run pre-commit hooks for all files", depends-on = [
    "pre-commit-install",
] }
pre-commit-install = { cmd = [
    "pre-commit",
    "install",
], description = "ðŸ”— Install pre-commit hooks" }

# === Python Version Features ===
[tool.pixi.feature.py310.dependencies]
python = "3.10.*"
[tool.pixi.feature.py311.dependencies]
python = "3.11.*"
[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.environments]
lab = { features = ["lab"], solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
lint = { features = ["lint"], no-default-feature = true }

# For Test on Github actions
py310 = { features = ["test", "py310"] }
py311 = { features = ["test", "py311"] }
py312 = { features = ["test", "py312"] }
