[project]
name = "xspider"
version = "1.0.0.20250517"
description = ""
authors = [
    {name = "mathewgeola",email = "mathewgeola@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sqlparse (>=0.5.3,<0.6.0)",
    "htmlmin (>=0.1.12,<0.2.0)",
    "arrow (>=1.3.0,<2.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
