[tool.poetry]
name = "nldi-xstool"
version = "0.12.15"
description = "Nldi Xstool"
authors = ["Richard McDonald <rmcd@usgs.gov>"]
license = "LICENSE.md"
readme = "README.md"
homepage = "https://code.usgs.gov/wma/nhgf/toolsteam/nldi-xstool"
repository = "https://code.usgs.gov/wma/nhgf/toolsteam/nldi-xstool"
documentation = "https://nldi-xstool.readthedocs.io"
packages = [
    { include = "nldi_xstool", from = "src" },
    { include = "_pygeoapi_process", from = "src" },
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://code.usgs.gov/wma/nhgf/toolsteam/nldi-xstool/-/releases"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
click = "^8.0"
pygeoapi = ">=0.11.0"
numpy = "^2"
geopandas = ">=0.11.0"
Shapely = "^2"
xarray = ">=2022.3.0"
dask = ">=2024.5.1"
netCDF4 = ">=1.5.8"
Bottleneck = ">=1.3.4"
numba = ">=0.55.1"
py3dep = "^0.19.0"
pygeohydro = "^0.19.0"
pynhd = "^0.19.0"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2.4"
safety = "<2.0.0"
coverage = {extras = ["toml"], version = "^5.4"}
typeguard = "^2.12.1"
xdoctest = {extras = ["colors"], version = "^0.15.5"}
sphinx = "<8.0.0"
sphinx-autobuild = ">2021.3.14"
pre-commit = "^2.13.0"
flake8 = "^7.1.0"
flake8-bandit = "^4.1.1"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.0"
darglint = "^1.8.0"
reorder-python-imports = "^2.6.0"
pre-commit-hooks = ">4.0.1"
sphinx-rtd-theme = ">0.5.2"
sphinx-click = ">3.0.1"
Pygments = "^2.9.0"
nox_poetry = "^1.0.3"
jupyterlab = "^3.2.4"
myst-parser = ">3.0.0"
recommonmark = "^0.7.1"
mypy = "^0.930"
advbumpversion = "^1.2.0"
nox = ">=2022.1.7"
black = "^23.11.0"
nbsphinx = "^0.9.4"
ipykernel = "^6.29.5"
bandit = "^1.7.9"
nbconvert = "^7.16.4"
nbformat = "^5.10.4"

[tool.poetry.scripts]
nldi-xstool = "nldi_xstool.__main__:main"

[tool.poetry2conda]
name = "nldi-xstool"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
omit = ["src/nldi_xstool/process/*", "src/nldi_xstool/__openChannel.py"]

[tool.coverage.run]
branch = true
source = ["nldi_xstool"]

[tool.coverage.report]
show_missing = true
fail_under = 70
omit = ["src/nldi_xstool/process/*", "src/nldi_xstool/__openChannel.py"]

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
no_implicit_reexport = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
warn_unused_ignores = false

[[tool.mypy.overrides]]
module = "noxfile"
warn_unreachable = false
disallow_untyped_decorators = false

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
