[tool.poetry]
name = "automatic-youtube-maker-story"
version = "0.5"
description = "Gerador de video de 1 minuto autom√°tico, utilizando ComfyUI, narration-xtts2, story-children-video-maker e story-chilren-gemma3"
authors = ["William Ferreira Linux <williambox37@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/illiamw/illiamw"
packages = [{include = "automatic_youtube_maker_story", from = "src"}]


[tool.poetry.dependencies]
python = "^3.11"
torch = {version = ">=2.3,<2.4", source = "pytorch-gpu"}
torchvision = {version = ">=0.18,<0.19", source = "pytorch-gpu"}
torchaudio = {version = ">=2.3,<2.4", source = "pytorch-gpu"}
gitpython = ">=3.1.44,<4.0.0"
requests = ">=2.32.3,<3.0.0"
pyyaml = ">=6.0.2,<7.0.0"
narration-xtts2 = ">=1.0.6,<2.0.0"
story-chilren-gemma3 = ">=0.1.21,<0.2.0"
story-children-video-maker = ">=0.1.2,<0.2.0"
google-api-python-client = ">=2.169.0,<3.0.0"
google-auth-oauthlib = ">=1.2.2,<2.0.0"
httplib2 = ">=0.22.0,<0.23.0"
oauth2client = ">=4.1.3,<5.0.0"
apiclient = ">=1.0.4,<2.0.0"
google-auth-httplib2 = ">=0.2.0,<0.3.0"
sageattention = ">=1.0.6,<2.0.0"
accelerate = ">=1.7.0,<2.0.0"
einops = ">=0.8.1,<0.9.0"
imageio-ffmpeg = ">=0.6.0,<0.7.0"
opencv-python = ">=4.11.0.86,<5.0.0.0"

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
