[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "secnex_notion_api"
version = "0.0.3"
authors = [
  { name="BjÃ¶rn Benouarets", email="bjorn@secnex.io" },
]
description = "A package to interact with the Notion API"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://github.com/secnex/notion-api"
Issues = "https://github.com/secnex/notion-api/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]