[tool.poetry]
name = "rpi_stt_tts_shell"
version = "0.3.0"
description = "Biblioteka STT i TTS dla Raspberry Pi"
authors = ["Tom Sapletta <info@softreck.com>"]
readme = "README.md"
packages = [{include = "rpi_stt_tts_shell"}]

[tool.poetry.dependencies]
python = "^3.7"
rpi-gpio = "^0.7.1"
adafruit-blinka = "^8.19.0"
adafruit-circuitpython-dht = "^3.7.8"
picamera = {version = "^1.13", optional = true}
paho-mqtt = "^2.2.1"
click = "^8.1.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.2.0"

[tool.poetry.extras]
camera = ["picamera"]

[tool.poetry.scripts]
rpi-example = "rpi_stt_tts_shell.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py37"]

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.7"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false

[[tool.mypy.overrides]]
module = ["RPi.*", "board", "digitalio", "busio", "picamera"]
ignore_missing_imports = true