[project]
name = "definit-db-py"
version = "0.1.1"
description = "DefinIT database"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["definit_db_py"]
include-package-data = true

[tool.setuptools.package-data]
"definit_db_py" = ["*.py", "data_md/**/*"]
