[project]
name = "jumpstarter-driver-snmp"
dynamic = [
    "version",
    "urls",
]
description = "SNMP driver"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
authors = [
    { name = "Benny Zlotnik", email = "bzlotnik@redhat.com" },
]
dependencies = [
    "jumpstarter==0.6.0",
    "pysnmp==7.1.16",
]

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-cov>=6.0.0",
    "pytest-anyio>=0.0.0",
    "pytest-asyncio>=0.0.0",
    "jumpstarter-testing",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
testpaths = [
    "jumpstarter_driver_snmp",
]
asyncio_mode = "auto"

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://jumpstarter.dev"
source_archive = "https://github.com/jumpstarter-dev/repo/archive/{commit_hash}.zip"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../../"

[tool.hatch.build.hooks.pin_jumpstarter]
name = "pin_jumpstarter"

[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
    "hatch-pin-jumpstarter",
]
build-backend = "hatchling.build"
