[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "zbyte"
version = "0.1.1"
description = "Python SDK for 0byte image generation and proof anchoring"
authors = [{name="0byte", email="nitinmewar28@gmail.com"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
keywords = ["ai", "proof", "solana", "image verification", "zero byte"]

dependencies = [
  "requests>=2.28",
  "pydantic>=1.10",
  "pillow",
  "diffusers",
  "transformers",
  "torch",
  "accelerate"
]

[project.urls]
"Homepage" = "https://www.0byte.tech"
"Source" = "https://github.com/0byte-lab/python-sdk"