[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["signals"]

[project]
name = "signals-py"
version = "0.1.0"
description = "send and receive signals"
readme = "README.md"
requires-python = ">=3.12"
maintainers = [
    {name = "amirreza",email = "amir.rsf1380@gmail.com"},
]
classifiers = [
    "Programming Language :: Python",
    "Development Status :: 4 - Beta" ,
    "Topic :: Utilities",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Typing :: Typed",
]
dependencies = [
    "asgiref>=3.8.1",
    "lazy-settings>=0.1.1",
]

[project.urls]
Homepage = "https://github.com/khiyavan/signals-py"
Issues = "https://github.com/khiyavan/signals-py/issues"

[tool.mypy]
exclude = ["tests/"]

[dependency-groups]
dev = [
    "anyio>=4.9.0",
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-mock>=3.14.0",
    "ruff>=0.11.10",
]

[lazy-settings]
SETTINGS_MODULE = "tests.settings"
