[project]
name = "geocr"
version = "1.1.0"
description = "GeOCR is a Python library for OCR, data cleaning, and historical geocoding using custom GeoJSON maps."
authors = [{ name="Joshua Vachon"}]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = [
  "opencv-python-headless>=4.11,<5.0",
  "numpy>=2.0,<3.0",
  "matplotlib>=3.10,<4.0",
  "pytesseract>=0.3,<1.0",
  "pillow>=11.2,<12.0",
  "ipython>=7.34,<9.0",
  "pandas>=2.2,<3.0",
  "geopandas>=1.0,<2.0",
  "shapely>=2.1,<3.0",
  "rapidfuzz>=3.13,<4.0"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["geocr"]

[tool.setuptools.package-data]
"geocr" = ["*.py"]