[build-system]
requires = ["flit_core"]
build-backend = "flit_core.buildapi"

[project]
name = "diao"
authors = [{name = "calcuis", email = "info@calcu.io"}]
description = "text-to-speech synthesis"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version"]

[project.urls]
GitHub = "https://github.com/calcuis/text-to-speech-synthesis"
Issues = "https://github.com/calcuis/text-to-speech-synthesis/issues"