[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ragformance"
version = "0.1.17"
description = "A library for generating dataset and evaluating these datasets on RAG based solutions"
readme = "README.md"
requires-python = ">=3.6"
authors = [
    { name="FOR Team", email="jonathan.sprauel@irt-saintexupery.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "forcolate",
    "sentence-transformers",
    "tqdm",
    "pytrec_eval",
    "plotly",
    "huggingface_hub",
    "datasets"
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["ragformance*", "ragformance.*"]

[project.urls]
"Homepage" = "https://github.com/FOR-sight-ai/RAGFORmance"
"Bug Tracker" = "https://github.com/FOR-sight-ai/RAGFORmance/issues"
