[project]
name = "geoaiagent"
version = "0.3.3"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]",
    "pathlib",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
geoaiagent = "geoaiagent.__main__:thisismain"

