[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "watson-osint"
version = "0.1.5"
description = "Watson - Powerful username search engine"
readme = "README.md"
authors = [
    {name = "margoul1", email = "github.pydoctor@gmail.com"}
]
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security",
    "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
]
keywords = ["osint", "username", "search", "social media", "investigation"]
dependencies = [
    "requests",
    "colorama",
    "beautifulsoup4",
    "fake_useragent",
    "dnspython",
    "google-api-python-client",
    "cloudscraper",
    "urllib3",
]
requires-python = ">=3.6"

[project.urls]
"Homepage" = "https://github.com/margoul1/watson"
"Bug Tracker" = "https://github.com/margoul1/watson/issues"

[project.scripts]
watson = "watson.__main__:main"
