[tool.poetry]
name = "pytopdrawer"
version = "0.0.8"
description = "Plot top files with python and matplotlib (mainly from POWHEG)"
authors = ["Alexander Puck Neuwirth <alexander@neuwirth-informatik.de>"]
readme = "README.md"
repository = "https://github.com/APN-Pucky/pytopdrawer"

[tool.poetry.dependencies]
python = "^3.8"
smpl = "*"
uncertainties = "*"

[tool.poetry.scripts]
pytopdrawer = "pytopdrawer.pytopdrawer:main"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
poetry-dynamic-versioning = {extras = ["plugin"], version = "^1.2.0"}

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.poetry-dynamic-versioning]
enable = false
vcs = "git"
style = "pep440"
dirty = true
# modified dunami default pattern without v
pattern = '(?x)(?# ignore whitespace)^((?P<epoch>\d+)!)?(?P<base>\d+(\.\d+)*)(?# v1.2.3 or v1!2000.1.2)([-._]?((?P<stage>[a-zA-Z]+)[-._]?(?P<revision>\d+)?))?(?# b0)(\+(?P<tagged_metadata>.+))?$(?# +linux)'
strict = true
format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}.{{ distance }}{% endif %}"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
addopts = [ "-v" ,"--cov=pytest" ,"--cov-config=.coveragerc" ,"--cov-append" ,"--cov-report=term " ,"--cov-report=xml" ,"--doctest-modules" ]
filterwarnings = [
    'ignore: pkg_resources is deprecated as an API:DeprecationWarning'
]

