[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "3DModelXpress"  # must be unique on PyPI
version = "0.0.1a0"
description = "Placeholder for future release"
readme = "README.md"
requires-python = ">=3.7"
authors = [{ name = "DataFre8 Team", email = "team@datafre8.com" }]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: 3"
]
